IBOVESPA = [
    "PETR4.SA", "VALE3.SA", "ITUB4.SA", "BBDC4.SA", "ABEV3.SA",
    "WEGE3.SA", "RENT3.SA", "BBAS3.SA", "LREN3.SA", "GGBR4.SA",
    "BPAC11.SA", "HAPV3.SA", "JBSS3.SA", "SUZB3.SA", "CSAN3.SA",
    "EQTL3.SA", "EGIE3.SA", "VIVT3.SA", "RADL3.SA", "TOTS3.SA",
]
